### ISSUE TITLE
[AttributesInVBA] - Overloaded default procedure?

### ISSUE THREAD

**Issue by elie-g** [Vitosh/VBA_personal#4]
Is it possible to create an overloaded default procedure?

So you could do something like this:
------------ _Class_ ------------
```vb
'...
Public Function DefaultProc() As Something
	Attribute '...
	'...
End Function

Public Function DefaultProc(ByVal myNumber As Integer) As Something
	Attribute '... ??
	'...
End Function

Public Function DefaultProc(ByVal myString As String) As Something
	Attribute '... ??
	'...
End Function
'...
```
------------ _Main_ ------------
```vb
Dim Instance As New MyClass
Debug.Print Instance
Debug.Print Instance("Joe")
Debug.Print Instance(1)
```

**Comment by Vitosh** [comment]
@DrunkenPoney  - give it a try and write a few tests. If it works, I will add it to the project.

**Comment by elie-g** [comment]
@Vitosh I tried it but I couldn't find any way to overload the default function/procedure. Though, I'm not an expert in VBA and there might be a way I don't know but a simple overload with the same procedure name but with different parameters does not work. I also tried to set the same `VB_UserMemId` attribute but it didn't work either.

**Comment by Vitosh** [comment]
@DrunkenPoney - Joel Spolsky has some ideas here:
https://stackoverflow.com/questions/64436/function-overloading-and-udf-in-excel-vba
(The guy literally put VBA in Excel, so he is a good source :)
